[package]
name = "etcommon"
version = "0.1.1"
license = "Apache-2.0"
authors = ["Wei Tang <hi@that.world>"]
description = "Apache-2 licensed common Ethereum structs shared by crates."
repository = "https://github.com/ethereumproject/etcommon"

[dependencies]
etcommon-rlp = "0.2"
etcommon-hexutil = "0.2"
etcommon-bigint = "0.2"
etcommon-block = "0.2"
etcommon-trie = "0.2"
etcommon-bloom = "0.2"
blockchain = "0.1"

[dev-dependencies]
sputnikvm = "0.5"
secp256k1-plus = "0.5"
rand = "0.3.12"
sha3 = "0.6"

[workspace]
members = [
  "./rlp",
  "./bigint",
  "./hexutil",
  "./block",
  "./trie",
  "./bloom",
]
